resources:
- name: repo
  type: git
  source:
    uri: https://github.com/aoldershaw/concourse-experiments.git

jobs:
- name: set
  plan:
  - get: repo
  - set_pipeline: my-child-pipeline
    file: repo/pipelines/simple.yml
