resources:
- name: repo
  type: git
  source:
    uri: https://github.com/aoldershaw/concourse-experiments.git

jobs:
- name: job
  plan:
  - task: echo
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: {repository: busybox}
      run:
        path: echo
        args: [((foo.bar))]
